In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

import numpy as np
import torch

np.set_printoptions(precision=3, suppress=True)
torch.set_printoptions(precision=2, linewidth=200)

In [2]:
# load model

from lagat.model import GNNPlanner

model_fpath = Path("../assets/pretrained/loss_best.pt")
model = GNNPlanner.reconstruct(model_fpath)
model.eval()

GNNPlanner(
  (encoder): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=242, out_features=256, bias=True)
    (2): ReLU()
    (3): Linear(in_features=256, out_features=256, bias=True)
    (4): ReLU()
  )
  (gnn): GAT(256, 256, num_layers=3)
  (decoder): Sequential(
    (0): Linear(in_features=256, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=256, bias=True)
    (3): ReLU()
    (4): Linear(in_features=256, out_features=5, bias=True)
  )
)

In [3]:
# setup grid config

from pogema import GridConfig

from lagat.utils import set_global_seeds

seed = 42

set_global_seeds(seed)
grid_config = GridConfig(
    num_agents=20,
    obs_radius=model.obs_radius,
    seed=seed,
    observation_type="MAPF",
    on_target="nothing",
    density=0.2,
    width=20,
    height=20,
)

In [4]:
# run model

from lagat.run_planners import run_neural_policy

%time env, all_actions, all_observations, all_terminated = run_neural_policy(model, grid_config, animation=True)

CPU times: user 386 ms, sys: 3.14 s, total: 3.53 s
Wall time: 289 ms


In [5]:
# visualize

env.save_animation("tmp.svg")

In [6]:
all_actions

[array([2, 4, 1, 3, 2, 2, 1, 2, 1, 4, 1, 2, 2, 4, 3, 3, 3, 1, 2, 3]),
 array([2, 2, 1, 3, 3, 2, 4, 4, 4, 1, 3, 2, 2, 4, 3, 1, 1, 1, 3, 2]),
 array([2, 2, 1, 3, 4, 2, 1, 4, 1, 1, 3, 3, 2, 1, 3, 1, 1, 1, 0, 2]),
 array([2, 4, 1, 3, 4, 4, 1, 4, 1, 1, 2, 0, 2, 1, 0, 1, 3, 1, 0, 3]),
 array([2, 4, 1, 1, 2, 4, 4, 1, 1, 4, 3, 0, 3, 1, 3, 1, 3, 1, 0, 2]),
 array([2, 4, 4, 1, 4, 4, 4, 1, 1, 4, 3, 0, 3, 1, 3, 1, 1, 1, 0, 3]),
 array([2, 2, 1, 4, 4, 4, 4, 1, 4, 1, 3, 0, 2, 1, 1, 4, 3, 1, 0, 3]),
 array([3, 4, 4, 4, 2, 4, 4, 1, 1, 1, 3, 0, 2, 1, 1, 3, 3, 1, 0, 3]),
 array([0, 2, 1, 4, 2, 4, 4, 1, 1, 4, 3, 0, 3, 1, 3, 1, 1, 1, 0, 1]),
 array([3, 4, 4, 4, 2, 1, 4, 1, 1, 1, 3, 0, 2, 3, 3, 3, 1, 1, 0, 1]),
 array([4, 4, 4, 1, 2, 1, 1, 4, 1, 1, 1, 0, 3, 1, 3, 1, 3, 1, 0, 0]),
 array([3, 1, 4, 1, 3, 0, 1, 1, 3, 1, 1, 0, 3, 1, 3, 3, 3, 1, 0, 0]),
 array([3, 0, 1, 3, 2, 0, 4, 1, 0, 4, 1, 0, 2, 1, 0, 0, 3, 4, 0, 0]),
 array([2, 0, 1, 1, 2, 0, 4, 4, 0, 4, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([3, 0, 1, 1, 

In [7]:
# makespan, number of agents, observation for one agent
len(all_observations), len(all_observations[0]), all_observations[0][0]

(29,
 20,
 {'obstacles': array([[0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.]], dtype=float32),
  'agents': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
         [0., 0